import Head from "next/head";
import Image from "next/image";
import styles from "../shared/styles/Home.module.css";
import { Button, CircularProgress, Dialog, Grid, Typography } from "@mui/material";
import { useState } from "react";

export default function Home() {
  const [OpenDialog, setOpenDialog] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Juego del ahorcado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Dialog /> */}

      <main className={styles.main}>
        <h1 className={styles.title}>Juego del ahorcado</h1>

 
      </main>

      <footer className={styles.footer}>
        Grupo 2
        <ul>
          <li>Gerson Rodriguez</li>
          <li>Cesar </li>
        </ul>
      </footer>
    </div>
  );
}
